# Generated by Django 3.2 on 2021-04-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrearSemillero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crearsemillero',
            name='codeSemillero',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='crearsemillero',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='crearsemillero',
            name='fechaFin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='crearsemillero',
            name='fechaInicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='crearsemillero',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='crearsemillero',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
