# Generated by Django 3.2 on 2021-04-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListadoSemilleros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeSemillero', models.IntegerField()),
                ('listadoSemillero', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Talleres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeSemillero', models.IntegerField()),
                ('talleresSemillero', models.TextField()),
            ],
        ),
    ]
